// Editable authoring examples. They are never published automatically.
export const exerciseExamples = [
  { level: "Básico", exerciseType: "listening_transcription", title: "Uma apresentação", prompt: "Escute e transcreva a frase em inglês.", speech: "Nice to meet you.", correctAnswer: "Nice to meet you.", explanation: "Nice to meet you é uma forma natural de cumprimentar alguém que você acabou de conhecer." },
  { level: "Básico", exerciseType: "correction", title: "Fale sobre ela", prompt: "Corrija a frase: She don't like coffee.", speech: "", correctAnswer: "She doesn't like coffee.", explanation: "Com she, usamos doesn't. O verbo principal continua na forma base: like." },
  { level: "Básico", exerciseType: "fill", title: "De onde você é?", prompt: "Complete apenas a palavra que falta: I ___ from Brazil.", speech: "", correctAnswer: "am", explanation: "O verbo to be com I é am: I am from Brazil." },
  { level: "Básico", exerciseType: "teacher_prompt", title: "Conheça alguém", prompt: "Pergunte o nome de uma pessoa em inglês.", speech: "", correctAnswer: "What is your name?", explanation: "What is your name? pergunta o nome. What's your name? também é natural; a professora pode cadastrá-la como resposta aceita." },
  { level: "Intermediário", exerciseType: "listening_transcription", title: "Um pedido educado", prompt: "Ouça e escreva a frase completa.", speech: "Could I have a glass of water, please?", correctAnswer: "Could I have a glass of water, please?", explanation: "Could I have…? faz um pedido educado. Observe a expressão a glass of water." },
  { level: "Intermediário", exerciseType: "situational", title: "Na cafeteria", prompt: "Peça um café de forma educada. Comece com Could I…", speech: "", correctAnswer: "Could I have a coffee, please?", explanation: "Could I have a coffee, please? combina pedido e cortesia. Evite traduzir literalmente eu quero." },
  { level: "Intermediário", exerciseType: "correction", title: "Uma experiência de vida", prompt: "Corrija: I have lived here since five years.", speech: "", correctAnswer: "I have lived here for five years.", explanation: "Use for para uma duração (five years) e since para o momento de início (2021)." },
  { level: "Intermediário", exerciseType: "fill", title: "Um plano para amanhã", prompt: "Complete: If it rains, we ___ stay at home.", speech: "", correctAnswer: "will", explanation: "Uma possibilidade futura pode usar if + presente e will + verbo na oração principal." },
  { level: "Avançado", exerciseType: "listening_transcription", title: "Mudança de planos", prompt: "Escute e transcreva, prestando atenção à estrutura verbal.", speech: "If I had known earlier, I would have called you.", correctAnswer: "If I had known earlier, I would have called you.", explanation: "A frase imagina um passado diferente: if + had known e would have called." },
  { level: "Avançado", exerciseType: "correction", title: "Precisão na comunicação", prompt: "Corrija: I look forward to hear from you.", speech: "", correctAnswer: "I look forward to hearing from you.", explanation: "Em look forward to, to é preposição e pede hearing, não hear." },
  { level: "Avançado", exerciseType: "fill", title: "Uma hipótese no passado", prompt: "Complete as três palavras: Had I known, I ___ differently.", speech: "", correctAnswer: "would have acted", explanation: "Had I known equivale a If I had known. A consequência usa would have + particípio." },
  { level: "Avançado", exerciseType: "teacher_prompt", title: "Reformule com precisão", prompt: "Reescreva usando despite: Although it was raining, we went out.", speech: "", correctAnswer: "Despite the rain, we went out.", explanation: "Despite é seguido de substantivo ou gerúndio. The rain transforma a oração em um grupo nominal." },
];
