"use client";
import { useEffect, useState } from 'react';
import type { LessonVideo } from '../lib/lesson-videos';
type Video = LessonVideo;
export function VideoLibraryManager({ lessons, revision }: { lessons: { id: number; title: string }[]; revision: string }) {
  const [videos, setVideos] = useState<Video[]>([]); const [edit, setEdit] = useState<Video | null>(null); const [copy, setCopy] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [refresh, setRefresh] = useState(0);
  useEffect(() => { const controller = new AbortController(); fetch('/api/admin/videos', { signal: controller.signal }).then(async r => { if (!r.ok) throw new Error('Não foi possível carregar os vídeos.'); return r.json(); }).then(d => setVideos(d.videos)).catch(e => { if (!controller.signal.aborted) setError(e.message); }); return () => controller.abort(); }, [revision, refresh]);
  async function save(video: Video, action: string) { setBusy(true); setError(''); try { const r = await fetch('/api/admin/videos', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...video, action }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setEdit(null); setRefresh(v => v + 1); } catch(e) { setError(e instanceof Error ? e.message : 'Falha ao salvar.'); } finally { setBusy(false); } }
  return <section className="video-library"><h2>Vídeos das aulas</h2><p>{videos.length} vídeos e trechos · novos uploads são adicionados, não substituídos.</p>{error && <p role="alert">{error}</p>}{videos.map(video => <article key={video.id}><video controls preload="none" src={`/api/videos?key=${encodeURIComponent(video.videoKey)}#t=${video.startSeconds}${video.endSeconds ? ',' + video.endSeconds : ''}`} /><div><strong>{video.title}</strong><small>{lessons.find(l => l.id === video.lessonId)?.title} · {(video.size / 1024 / 1024).toFixed(1)} MB</small><small>Trecho: {video.startSeconds}s até {video.endSeconds === null ? 'o fim' : video.endSeconds + 's'}</small><div className="video-actions"><button className="outline-button" onClick={() => { setEdit(video); setCopy(false); }}>Editar / mover</button><button className="outline-button" onClick={() => { setEdit({ ...video, title: video.title + ' — trecho' }); setCopy(true); }}>Usar trecho em outra aula</button><button className="outline-button" disabled={busy} onClick={() => { if (window.confirm('Remover este vídeo da aula? O arquivo original será preservado; outros trechos não serão excluídos.')) void save(video, 'delete'); }}>Remover da aula</button></div></div></article>)}{!videos.length && <p>Nenhum vídeo enviado.</p>}{edit && <div className="admin-editor-backdrop"><form className="admin-editor" onSubmit={event => { event.preventDefault(); void save(edit, copy ? 'copy' : 'edit'); }}><h2>{copy ? 'Reutilizar trecho' : 'Editar vídeo'}</h2><p>O intervalo define o trecho reproduzido. O arquivo original não é recortado nem duplicado.</p><label>Título<input required value={edit.title} onChange={e => setEdit({ ...edit, title: e.target.value })} /></label><label>Aula<select value={edit.lessonId} onChange={e => setEdit({ ...edit, lessonId: Number(e.target.value) })}>{lessons.map(l => <option key={l.id} value={l.id}>{l.title}</option>)}</select></label><div className="form-row"><label>Início (segundos)<input type="number" min="0" required value={edit.startSeconds} onChange={e => setEdit({ ...edit, startSeconds: Number(e.target.value) })} /></label><label>Fim (vazio = até o fim)<input type="number" min={edit.startSeconds + 1} value={edit.endSeconds ?? ''} onChange={e => setEdit({ ...edit, endSeconds: e.target.value ? Number(e.target.value) : null })} /></label></div><label>Ordem na aula<input type="number" min="0" value={edit.position} onChange={e => setEdit({ ...edit, position: Number(e.target.value) })} /></label>{error && <p role="alert">{error}</p>}<div className="editor-actions"><button type="button" onClick={() => setEdit(null)}>Cancelar</button><button disabled={busy}>{busy ? 'Salvando…' : 'Salvar vídeo'}</button></div></form></div>}</section>;
}
