-- Right Way: non-destructive alignment of the current D1 schema with Supabase Postgres.
-- This migration intentionally does not DROP tables, columns or rows.
-- Existing legacy Supabase columns are retained and backfilled into the names used by the current app.

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  level text not null default 'Básico',
  placement_score integer not null default 0,
  status text not null default 'Ativo',
  created_at text not null
);

create table if not exists public.course_modules (
  id bigint generated by default as identity primary key,
  title text not null,
  level text not null,
  description text not null default '',
  status text not null default 'Publicado',
  position integer not null default 0,
  cover_key text,
  cover_mobile_key text,
  cover_fit text not null default 'cover',
  cover_zoom integer not null default 100,
  cover_overlay integer not null default 24,
  cover_position_x integer not null default 50,
  cover_position_y integer not null default 50
);

create table if not exists public.course_sections (
  id bigint generated by default as identity primary key,
  module_id bigint not null,
  title text not null,
  description text not null default '',
  status text not null default 'Publicado',
  position integer not null default 0,
  cover_key text,
  cover_mobile_key text,
  cover_fit text not null default 'cover',
  cover_zoom integer not null default 100,
  cover_overlay integer not null default 24,
  cover_position_x integer not null default 50,
  cover_position_y integer not null default 50
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  section_id bigint not null,
  title text not null,
  description text not null default '',
  duration text not null default '10 min',
  lesson_type text not null default 'Vídeo + prática',
  status text not null default 'Publicado',
  position integer not null default 0,
  smart_rotation integer not null default 0,
  video_key text,
  video_name text,
  video_size bigint,
  thumbnail_key text,
  thumbnail_mobile_key text,
  thumbnail_fit text not null default 'cover',
  thumbnail_zoom integer not null default 100,
  thumbnail_overlay integer not null default 20,
  thumbnail_position_x integer not null default 50,
  thumbnail_position_y integer not null default 50
);

create table if not exists public.lesson_exercises (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null,
  exercise_type text not null default 'choice',
  category text not null default 'Compreensão',
  title text not null,
  prompt text not null,
  options_json text,
  correct_answer text not null,
  accepted_answers_json text,
  explanation text not null default '',
  speech text,
  audio_key text,
  audio_name text,
  skills_json text,
  rotation_variants_json text not null default '[]',
  status text not null default 'Publicado',
  position integer not null default 0
);

create table if not exists public.user_accounts (
  id bigint generated by default as identity primary key,
  email text not null,
  full_name text not null,
  password_hash text not null,
  password_salt text not null,
  role text not null default 'student',
  status text not null default 'active',
  level text not null default 'Começando do zero',
  placement_score integer not null default 0,
  goal text,
  daily_minutes integer not null default 10,
  token_version integer not null default 1,
  must_change_password integer not null default 0,
  created_at text not null,
  updated_at text not null,
  last_login_at text
);

create table if not exists public.auth_sessions (
  id text primary key,
  user_id bigint not null,
  refresh_token_hash text not null,
  ip_hash text,
  user_agent text,
  expires_at text not null,
  created_at text not null,
  revoked_at text
);

create table if not exists public.login_attempts (
  identifier text primary key,
  failed_count integer not null default 0,
  locked_until text,
  updated_at text not null
);

create table if not exists public.placement_attempts (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  score integer not null,
  total_questions integer not null,
  resulting_level text not null,
  answers_json text not null,
  created_at text not null
);

create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  lesson_id bigint,
  lesson_slug text not null,
  progress_percent integer not null default 0,
  best_score integer not null default 0,
  attempts_count integer not null default 0,
  completed_at text,
  updated_at text not null
);

create table if not exists public.exercise_attempts (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  lesson_id bigint,
  lesson_slug text not null,
  score integer not null,
  total integer not null,
  answers_json text,
  created_at text not null
);

create table if not exists public.practice_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  lesson_id bigint not null,
  current_index integer not null default 0,
  answers_json text not null default '[]',
  score integer not null default 0,
  total integer not null default 0,
  status text not null default 'active',
  exercise_plan_json text not null default '[]',
  created_at text not null,
  updated_at text not null
);

create table if not exists public.video_progress (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  lesson_id bigint not null,
  position_seconds integer not null default 0,
  duration_seconds integer not null default 0,
  progress_percent integer not null default 0,
  status text not null default 'not_started',
  updated_at text not null
);

create table if not exists public.section_exams (
  id bigint generated by default as identity primary key,
  section_id bigint not null,
  title text not null,
  description text not null default '',
  status text not null default 'Rascunho',
  pass_score integer not null default 70,
  position integer not null default 1
);

create table if not exists public.section_exam_questions (
  id bigint generated by default as identity primary key,
  exam_id bigint not null,
  question_type text not null default 'choice',
  category text not null default 'Avaliação',
  prompt text not null,
  options_json text,
  correct_answer text not null,
  accepted_answers_json text,
  explanation text not null default '',
  status text not null default 'Rascunho',
  position integer not null default 0
);

create table if not exists public.section_exam_attempts (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  exam_id bigint not null,
  score integer not null,
  total integer not null,
  percentage integer not null,
  passed integer not null default 0,
  answers_json text not null default '[]',
  created_at text not null
);

create table if not exists public.lesson_videos (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null,
  video_key text not null,
  title text not null,
  size bigint not null default 0,
  position integer not null default 0,
  start_seconds integer not null default 0,
  end_seconds integer
);

create table if not exists public.video_item_progress (
  user_id bigint not null,
  video_id bigint not null,
  position_seconds integer not null default 0,
  duration_seconds integer not null default 0,
  completed integer not null default 0,
  updated_at text not null
);

-- Add every column introduced after the first Supabase foundation, without removing legacy columns.
alter table public.course_modules add column if not exists cover_key text;
alter table public.course_modules add column if not exists cover_mobile_key text;
alter table public.course_modules add column if not exists cover_fit text not null default 'cover';
alter table public.course_modules add column if not exists cover_zoom integer not null default 100;
alter table public.course_modules add column if not exists cover_overlay integer not null default 24;
alter table public.course_modules add column if not exists cover_position_x integer not null default 50;
alter table public.course_modules add column if not exists cover_position_y integer not null default 50;

alter table public.course_sections add column if not exists description text not null default '';
alter table public.course_sections add column if not exists status text not null default 'Publicado';
alter table public.course_sections add column if not exists cover_key text;
alter table public.course_sections add column if not exists cover_mobile_key text;
alter table public.course_sections add column if not exists cover_fit text not null default 'cover';
alter table public.course_sections add column if not exists cover_zoom integer not null default 100;
alter table public.course_sections add column if not exists cover_overlay integer not null default 24;
alter table public.course_sections add column if not exists cover_position_x integer not null default 50;
alter table public.course_sections add column if not exists cover_position_y integer not null default 50;

alter table public.lessons add column if not exists description text not null default '';
alter table public.lessons add column if not exists smart_rotation integer not null default 0;
alter table public.lessons add column if not exists video_key text;
alter table public.lessons add column if not exists video_name text;
alter table public.lessons add column if not exists video_size bigint;
alter table public.lessons add column if not exists thumbnail_key text;
alter table public.lessons add column if not exists thumbnail_mobile_key text;
alter table public.lessons add column if not exists thumbnail_fit text not null default 'cover';
alter table public.lessons add column if not exists thumbnail_zoom integer not null default 100;
alter table public.lessons add column if not exists thumbnail_overlay integer not null default 20;
alter table public.lessons add column if not exists thumbnail_position_x integer not null default 50;
alter table public.lessons add column if not exists thumbnail_position_y integer not null default 50;

alter table public.lesson_exercises add column if not exists options_json text;
alter table public.lesson_exercises add column if not exists accepted_answers_json text;
alter table public.lesson_exercises add column if not exists audio_key text;
alter table public.lesson_exercises add column if not exists audio_name text;
alter table public.lesson_exercises add column if not exists skills_json text;
alter table public.lesson_exercises add column if not exists rotation_variants_json text not null default '[]';

alter table public.practice_sessions add column if not exists exercise_plan_json text not null default '[]';

-- Preserve old Supabase foundation data by copying legacy column values into the current names.
do $$
begin
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='course_modules' and column_name='cover_path') then
    execute 'update public.course_modules set cover_key = coalesce(cover_key, cover_path) where cover_path is not null';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='course_modules' and column_name='cover_mobile_path') then
    execute 'update public.course_modules set cover_mobile_key = coalesce(cover_mobile_key, cover_mobile_path) where cover_mobile_path is not null';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='course_sections' and column_name='cover_path') then
    execute 'update public.course_sections set cover_key = coalesce(cover_key, cover_path) where cover_path is not null';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='course_sections' and column_name='cover_mobile_path') then
    execute 'update public.course_sections set cover_mobile_key = coalesce(cover_mobile_key, cover_mobile_path) where cover_mobile_path is not null';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='lessons' and column_name='video_path') then
    execute 'update public.lessons set video_key = coalesce(video_key, video_path) where video_path is not null';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='lessons' and column_name='thumbnail_path') then
    execute 'update public.lessons set thumbnail_key = coalesce(thumbnail_key, thumbnail_path) where thumbnail_path is not null';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='lessons' and column_name='thumbnail_mobile_path') then
    execute 'update public.lessons set thumbnail_mobile_key = coalesce(thumbnail_mobile_key, thumbnail_mobile_path) where thumbnail_mobile_path is not null';
  end if;

  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='lesson_exercises' and column_name='options') then
    execute 'update public.lesson_exercises set options_json = coalesce(options_json, options::text) where options is not null';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='lesson_exercises' and column_name='accepted_answers') then
    execute 'update public.lesson_exercises set accepted_answers_json = coalesce(accepted_answers_json, accepted_answers::text) where accepted_answers is not null';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='lesson_exercises' and column_name='skills') then
    execute 'update public.lesson_exercises set skills_json = coalesce(skills_json, skills::text) where skills is not null';
  end if;

  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='placement_attempts' and column_name='answers') then
    execute 'alter table public.placement_attempts add column if not exists answers_json text';
    execute 'update public.placement_attempts set answers_json = coalesce(answers_json, answers::text) where answers is not null';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='exercise_attempts' and column_name='answers') then
    execute 'alter table public.exercise_attempts add column if not exists answers_json text';
    execute 'update public.exercise_attempts set answers_json = coalesce(answers_json, answers::text) where answers is not null';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='practice_sessions' and column_name='answers') then
    execute 'alter table public.practice_sessions add column if not exists answers_json text';
    execute 'update public.practice_sessions set answers_json = coalesce(answers_json, answers::text) where answers is not null';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='section_exam_questions' and column_name='options') then
    execute 'alter table public.section_exam_questions add column if not exists options_json text';
    execute 'update public.section_exam_questions set options_json = coalesce(options_json, options::text) where options is not null';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='section_exam_questions' and column_name='accepted_answers') then
    execute 'alter table public.section_exam_questions add column if not exists accepted_answers_json text';
    execute 'update public.section_exam_questions set accepted_answers_json = coalesce(accepted_answers_json, accepted_answers::text) where accepted_answers is not null';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='section_exam_attempts' and column_name='answers') then
    execute 'alter table public.section_exam_attempts add column if not exists answers_json text';
    execute 'update public.section_exam_attempts set answers_json = coalesce(answers_json, answers::text) where answers is not null';
  end if;
end $$;

-- The live app stores booleans as 0/1. Convert only these Right Way columns if the old foundation used PostgreSQL booleans.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='user_accounts'
      and column_name='must_change_password' and data_type='boolean'
  ) then
    alter table public.user_accounts
      alter column must_change_password drop default,
      alter column must_change_password type integer using (case when must_change_password then 1 else 0 end),
      alter column must_change_password set default 0;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='section_exam_attempts'
      and column_name='passed' and data_type='boolean'
  ) then
    alter table public.section_exam_attempts
      alter column passed drop default,
      alter column passed type integer using (case when passed then 1 else 0 end),
      alter column passed set default 0;
  end if;
end $$;

-- Constraints required by ON CONFLICT statements in the current application.
create unique index if not exists students_email_unique on public.students(email);
create unique index if not exists user_accounts_email_unique on public.user_accounts(email);
create unique index if not exists lesson_progress_user_slug_unique on public.lesson_progress(user_id, lesson_slug);
create unique index if not exists practice_sessions_user_lesson_unique on public.practice_sessions(user_id, lesson_id);
create unique index if not exists video_progress_user_lesson_unique on public.video_progress(user_id, lesson_id);
create unique index if not exists section_exams_section_unique on public.section_exams(section_id);
create unique index if not exists video_item_progress_user_video_unique on public.video_item_progress(user_id, video_id);

create index if not exists lesson_exercises_lesson_status_position_idx on public.lesson_exercises(lesson_id, status, position);
create index if not exists section_exam_questions_exam_status_position_idx on public.section_exam_questions(exam_id, status, position);
create index if not exists section_exam_attempts_user_exam_idx on public.section_exam_attempts(user_id, exam_id);
create index if not exists lesson_videos_lesson_position_idx on public.lesson_videos(lesson_id, position);

-- Keep direct REST access closed. The Vercel server connects with the database credential.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'students','course_modules','course_sections','lessons','lesson_exercises',
    'user_accounts','auth_sessions','login_attempts','placement_attempts',
    'lesson_progress','exercise_attempts','practice_sessions','video_progress',
    'section_exams','section_exam_questions','section_exam_attempts',
    'lesson_videos','video_item_progress'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
  end loop;
end $$;

-- Private media bucket. Existing objects are never overwritten by this statement.
insert into storage.buckets (id, name, public)
values ('course-media', 'course-media', false)
on conflict (id) do update set public = false;

-- Advance identity/serial sequences after imported rows so future inserts never reuse an existing id.
do $$
declare
  table_name text;
  sequence_name text;
  maximum_id bigint;
begin
  foreach table_name in array array[
    'students','course_modules','course_sections','lessons','lesson_exercises',
    'user_accounts','placement_attempts','lesson_progress','exercise_attempts',
    'practice_sessions','video_progress','section_exams','section_exam_questions',
    'section_exam_attempts','lesson_videos'
  ]
  loop
    sequence_name := pg_get_serial_sequence(format('public.%I', table_name), 'id');
    if sequence_name is not null then
      execute format('select coalesce(max(id), 0) from public.%I', table_name) into maximum_id;
      perform setval(sequence_name, greatest(maximum_id, 1), maximum_id > 0);
    end if;
  end loop;
end $$;
