create table public.students (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  level text not null default 'Básico',
  placement_score integer not null default 0 check (placement_score >= 0),
  status text not null default 'Ativo',
  created_at timestamptz not null default now()
);

create table public.course_modules (
  id bigint generated by default as identity primary key,
  title text not null,
  level text not null,
  description text not null default '',
  status text not null default 'Publicado',
  position integer not null default 0,
  cover_path text,
  cover_mobile_path text,
  cover_fit text not null default 'cover',
  cover_zoom integer not null default 100,
  cover_overlay integer not null default 24,
  cover_position_x integer not null default 50,
  cover_position_y integer not null default 50
);

create table public.course_sections (
  id bigint generated by default as identity primary key,
  module_id bigint not null references public.course_modules(id) on delete cascade,
  title text not null,
  description text not null default '',
  status text not null default 'Publicado',
  position integer not null default 0,
  cover_path text,
  cover_mobile_path text,
  cover_fit text not null default 'cover',
  cover_zoom integer not null default 100,
  cover_overlay integer not null default 24,
  cover_position_x integer not null default 50,
  cover_position_y integer not null default 50
);

create table public.lessons (
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.course_sections(id) on delete cascade,
  title text not null,
  description text not null default '',
  duration text not null default '10 min',
  lesson_type text not null default 'Vídeo + prática',
  status text not null default 'Publicado',
  position integer not null default 0,
  video_path text,
  video_name text,
  video_size bigint,
  thumbnail_path text,
  thumbnail_mobile_path text,
  thumbnail_fit text not null default 'cover',
  thumbnail_zoom integer not null default 100,
  thumbnail_overlay integer not null default 20,
  thumbnail_position_x integer not null default 50,
  thumbnail_position_y integer not null default 50
);

create table public.user_accounts (
  id bigint generated by default as identity primary key,
  email text not null unique,
  full_name text not null,
  password_hash text not null,
  password_salt text not null,
  role text not null default 'student',
  status text not null default 'active',
  level text not null default 'Começando do zero',
  placement_score integer not null default 0 check (placement_score >= 0),
  goal text,
  daily_minutes integer not null default 10 check (daily_minutes > 0),
  token_version integer not null default 1 check (token_version > 0),
  must_change_password boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);

create table public.auth_sessions (
  id text primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  refresh_token_hash text not null,
  ip_hash text,
  user_agent text,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table public.login_attempts (
  identifier text primary key,
  failed_count integer not null default 0 check (failed_count >= 0),
  locked_until timestamptz,
  updated_at timestamptz not null default now()
);

create table public.placement_attempts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  score integer not null,
  total_questions integer not null check (total_questions > 0),
  resulting_level text not null,
  answers jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table public.lesson_exercises (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  exercise_type text not null default 'choice',
  category text not null default 'Compreensão',
  title text not null,
  prompt text not null,
  options jsonb,
  correct_answer text not null,
  accepted_answers jsonb,
  explanation text not null default '',
  speech text,
  skills jsonb,
  status text not null default 'Publicado',
  position integer not null default 0
);

create table public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  lesson_id bigint references public.lessons(id) on delete set null,
  lesson_slug text not null,
  progress_percent integer not null default 0 check (progress_percent between 0 and 100),
  best_score integer not null default 0,
  attempts_count integer not null default 0 check (attempts_count >= 0),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (user_id, lesson_slug)
);

create table public.exercise_attempts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  lesson_id bigint references public.lessons(id) on delete set null,
  lesson_slug text not null,
  score integer not null,
  total integer not null,
  answers jsonb,
  created_at timestamptz not null default now()
);

create table public.practice_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  current_index integer not null default 0 check (current_index >= 0),
  answers jsonb not null default '[]'::jsonb,
  score integer not null default 0,
  total integer not null default 0,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, lesson_id)
);

create table public.video_progress (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  position_seconds integer not null default 0 check (position_seconds >= 0),
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  progress_percent integer not null default 0 check (progress_percent between 0 and 100),
  status text not null default 'not_started',
  updated_at timestamptz not null default now(),
  unique (user_id, lesson_id)
);

create table public.section_exams (
  id bigint generated by default as identity primary key,
  section_id bigint not null unique references public.course_sections(id) on delete cascade,
  title text not null,
  description text not null default '',
  status text not null default 'Rascunho',
  pass_score integer not null default 70 check (pass_score between 0 and 100),
  position integer not null default 1
);

create table public.section_exam_questions (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references public.section_exams(id) on delete cascade,
  question_type text not null default 'choice',
  category text not null default 'Avaliação',
  prompt text not null,
  options jsonb,
  correct_answer text not null,
  accepted_answers jsonb,
  explanation text not null default '',
  status text not null default 'Rascunho',
  position integer not null default 0
);

create table public.section_exam_attempts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  exam_id bigint not null references public.section_exams(id) on delete cascade,
  score integer not null,
  total integer not null,
  percentage integer not null check (percentage between 0 and 100),
  passed boolean not null default false,
  answers jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index course_sections_module_position_idx on public.course_sections(module_id, position, id);
create index lessons_section_status_position_idx on public.lessons(section_id, status, position, id);
create index lesson_exercises_lesson_status_position_idx on public.lesson_exercises(lesson_id, status, position, id);
create index auth_sessions_user_active_idx on public.auth_sessions(user_id, revoked_at, expires_at);
create index auth_sessions_refresh_hash_idx on public.auth_sessions(refresh_token_hash);
create index placement_attempts_user_created_idx on public.placement_attempts(user_id, created_at desc);
create index exercise_attempts_user_lesson_idx on public.exercise_attempts(user_id, lesson_id, created_at desc);
create index section_exam_questions_exam_status_position_idx on public.section_exam_questions(exam_id, status, position, id);
create index section_exam_attempts_user_exam_idx on public.section_exam_attempts(user_id, exam_id, created_at desc);

alter table public.students enable row level security;
alter table public.course_modules enable row level security;
alter table public.course_sections enable row level security;
alter table public.lessons enable row level security;
alter table public.user_accounts enable row level security;
alter table public.auth_sessions enable row level security;
alter table public.login_attempts enable row level security;
alter table public.placement_attempts enable row level security;
alter table public.lesson_exercises enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.exercise_attempts enable row level security;
alter table public.practice_sessions enable row level security;
alter table public.video_progress enable row level security;
alter table public.section_exams enable row level security;
alter table public.section_exam_questions enable row level security;
alter table public.section_exam_attempts enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
